% function y = block_Htransf(x,iomUh,iomUt,HMt,HMv,HMut,HMuv)
%BLOCK_HCTRANSF y = block_Hctransf(x,iomUh,iomUt,HMt,HMv,HMut,HMuv)
%   Gives block hilbert transform for a signal x = [t; u; v],
%   with a uniform grid in the middle u part.
%   HILBERT = [ HMt [HMut; @hilbert; HMuv] HMv ].
%   HMt,HMv,HMut,HMuv are generated by block_Htransf_mat
%   x(iomUh:iomUt) == u.
%   y = 1i*block_Hctransf(x,iomUh,iomUt,HMt,HMv,HMut,HMuv) + x;

function y = block_Htransf(x,iomUh,iomUt,HMt,HMv,HMut,HMuv)
y = 1i*block_Hctransf(x,iomUh,iomUt,HMt,HMv,HMut,HMuv) + x;

end
